

def get_technames():
    return [
        "Achilles Targeting Unit",
        "Adamantium Armor",
        "Advanced City Planning",
        "Advanced Damage Control",
        "Alien Management Center",
        "Android Farmers",
        "Android Scientists",
        "Android Workers",
        "Anti-Gravity Harness",
        "Anti-Matter Bomb",
        "Anti-Matter Drive",
        "Anti-Matter Torpedoes",
        "Anti-Missile Rockets",
        "Armor Barracks",
        "Artemis System Net",
        "Artificial Planet",
        "Assault Shuttles",
        "Astro University",
        "Atmospheric Renewer",
        "Augmented Engines",
        "Autolab",
        "Automated Factories",
        "Automated Repair Unit",
        "Battleoids",
        "Battle Pods",
        "Battle Scanner",
        "Battlestation",
        "Bio-Terminator",
        "Biomorphic Fungi",
        "Black Hole Generator",
        "Bomber Bays",
        "Capitol",
        "Class I Shield",
        "Class III Shield",
        "Class V Shield",
        "Class VII Shield",
        "Class X Shield",
        "Cloaking Device",
        "Cloning Center",
        "Colony Base",
        "Colony Ship",
        "Confederation",
        "Cyber-Security Link",
        "Cybertronic Computer",
        "Damper Field",
        "Dauntless Guidance System",
        "Death Ray",
        "Death Spores",
        "Deep Core Mining",
        "Core Waste Dumps",
        "Deuterium Fuel Cells",
        "Dimensional Portal",
        "Displacement Device",
        "Disrupter Cannon",
        "Doom Star Construction",
        "Reinforced Hull",
        "ECM Jammer",
        "Electronic Computer",
        "Emissions Guidance System",
        "Energy Absorber",
        "Biospheres",
        "Evolutionary Mutation",
        "Extended Fuel Tanks",
        "Fast Missile Racks",
        "Federation",
        "Fighter Bays",
        "Fighter Garrison",
        "Food Replicators",
        "Freighters",
        "Fusion Beam",
        "Fusion Bomb",
        "Fusion Drive",
        "Fusion Rifle",
        "Gaia Transformation",
        "Galactic Currency Exchange",
        "Galactic Cybernet",
        "Galactic Unification",
        "Gauss Auto-Cannon",
        "Graviton Beam",
        "Gyro Destabilizer",
        "Hard Shields",
        "Heavy Armor",
        "Heavy Fighter Bays",
        "Heightened Intelligence",
        "High Energy Focus",
        "Holo Simulator",
        "Hydroponic Farms",
        "Hyper Drive",
        "MegaFluxers",
        "Hyper-X Capacitors",
        "Hyperspace Communications",
        "Imperium",
        "Inertial Nullifier",
        "Inertial Stabilizer",
        "Interphased Drive",
        "Ion Drive",
        "Ion Pulse Cannon",
        "Iridium Fuel Cells",
        "Jump Gate",
        "Laser Cannon",
        "Laser Rifle",
        "Lightning Field",
        "Marine Barracks",
        "Mass Driver",
        "Mauler Device",
        "Merculite Missile",
        "Microbiotics",
        "Microlite Construction",
        "Outpost Ship",
        "Moleculartronic Computer",
        "Multi-Wave Ecm Jammer",
        "Multi-Phased Shields",
        "Nano Disassemblers",
        "Neural Scanner",
        "Neutron Blaster",
        "Neutron Scanner",
        "Neutronium Armor",
        "Neutronium Bomb",
        "Nuclear Bomb",
        "Nuclear Drive",
        "Nuclear Missile",
        "Optronic Computer",
        "Particle Beam",
        "Personal Shield",
        "Phase Shifter",
        "Phasing Cloak",
        "Phasor",
        "Phasor Rifle",
        "Planetary Barrier Shield",
        "Planetary Flux Shield",
        "Planetary Gravity Generator",
        "Planetary Missile Base",
        "Ground Batteries",
        "Planetary Radiation Shield",
        "Planetary Stock Exchange",
        "Planetary Supercomputer",
        "Plasma Cannon",
        "Plasma Rifle",
        "Plasma Torpedoes",
        "Plasma Web",
        "Pleasure Dome",
        "Pollution Processor",
        "Positronic Computer",
        "Powered Armor",
        "Pulse Rifle",
        "Proton Torpedoes",
        "Psionics",
        "Pulsar",
        "Pulson Missile",
        "Quantum Detonator",
        "Rangemaster Unit",
        "Recyclotron",
        "Reflection Field",
        "Robotic Factory",
        "Research Laboratory",
        "Robo-Miners",
        "Space Scanner",
        "Scout Lab",
        "Security Stations",
        "Sensors",
        "Shield Capacitors",
        "Soil Enrichment",
        "Space Academy",
        "Spaceport",
        "Spatial Compressor",
        "Spy Network",
        "Standard Fuel Cells",
        "Star Base",
        "Star Fortress",
        "Star Gate",
        "Stasis Field",
        "Stealth Field",
        "Stealth Suit",
        "Stellar Converter",
        "Structural Analyzer",
        "Sub-Space Communications",
        "Sub-Space Teleporter",
        "Subterranean Farms",
        "Survival Pods",
        "Tachyon Communications",
        "Tachyon Scanner",
        "Telepathic Training",
        "Terraforming",
        "Thorium Fuel Cells",
        "Time Warp Facilitator",
        "Titan Construction",
        "Titanium Armor",
        "Tractor Beam",
        "Transport",
        "Transporters",
        "Tritanium Armor",
        "Troop Pods",
        "Universal Antidote",
        "Uridium Fuel Cells",
        "Virtual Reality Network",
        "Warp Dissipater",
        "Warp Interdictor",
        "Weather Control System",
        "Wide Area Jammer",
        "Xeno Psychology",
        "Xentronium Armor",
        "Zeon Missile",
        "Zortrium Armor"
    ]
    
# end func get_technames
